defaults:
  - model: refine_u
  - training: default
  - optional experiment: null
  - _self_

data:
  dir: data/
  lr_dim: 160
  hr_dim: 268
  cache_dir: data/

wandb:
  project: refine_u
  enabled: true
  group: null

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
